#!/bin/sh
# File generated by ocamlbuild

cd /home-reseau/flardeux/compilation/tp3/_build

rm -f lexer.cmi
rm -f lexer.cmo
rm -f lexer.cmx
rm -f lexer.ml
rm -f lexer.ml.depends
rm -f lexer.o
rm -f main.cmi
rm -f main.cmo
rm -f main.cmx
rm -f main.ml.depends
rm -f main.o
rm -f parser.cmx
rm -f parser.ml
rm -f parser.ml.depends
rm -f parser.mli
rm -f parser.mli.depends
rm -f parser.o
# Also clean the script itself
rm -f /home-reseau/flardeux/compilation/tp3/_build/_build/sanitize.sh
